[package]
name = "uncage"
version = "0.1.0"
authors = ["eater <=@eater.me>"]
edition = "2021"

[workspace]
members = [
  "uncage-client",
  "uncage-model",
  "uncage-model-proc-macro",
]

[workspace.dependencies]
uncage-client = { path = "uncage-client" }
uncage-model = { path = "uncage-model" }
uncage-model-proc-macro = { path = "uncage-model-proc-macro" }

[dependencies]
uncage-client = { workspace = true }
uncage-model = { workspace = true }

# compile dependencies with optimizations in dev mode
# see: https://doc.rust-lang.org/stable/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3
debug = true
