[package]
name = "uncage-patcher"
version = "0.1.0"
authors = ["eater <=@eater.me>"]
edition = "2018"

[dependencies]
uncage-model = { path = "../uncage-model" }
anyhow = "1.0.40"
byteorder = "1.4.3"

bytes = "1.0.1"
serde_json = "1.0.64"

[dev-dependencies]
brotli = "3.3.0"
